import "./globals.css";
import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";

const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
	weight: ["300", "400", "500", "700", "900"],
});
const openSans = Open_Sans({
	subsets: ["latin"],
	variable: "--font-opensans",
	display: "swap",
	weight: ["300", "400", "500", "700", "800"],
});

export const metadata: Metadata = {
	title: "Sport Odds",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang="en"
			className={`${inter.variable} ${openSans.variable} font-sans`}
		>
			<body
				suppressHydrationWarning
				className="bg-body text-white scrollbar scrollbar-w-[6px] scrollbar-thumb-gray-600 scrollbar-track-header scrollbar-thumb-rounded-md"
			>
				<div className="relative max-w-[1600px] mx-auto">
					{children}
				</div>
			</body>
		</html>
	);
}
